import type { Metadata } from "next";
import { Stick_No_Bills } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const stickNoBills = Stick_No_Bills({
  variable: "--font-stick-no-bills",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BRUM V.5.0",
  description: "Generated by 18",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${stickNoBills.variable} antialiased bg-slate-200/75`}>
        <div
          style={{ fontFamily: "var(--font-stick-no-bills" }}
          className="antialiased justify-center items-center flex bg-slate-800 text-white font-semibold text-xl py-2.5"
        >
          <Link href={"/"}>Herzlich willkommen</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
